preprocessor:
  categorical:
    transformer: OneHotEncoder
    features:
      - 'Marital Status'
  numerical:
    transformer: RobustScaler
    features:
      - 'Experience'
      - 'Age'

regressor:
  model: RandomForestRegressor
  params:
    n_estimators: [50, 100, 200]
    max_depth: [null, 10, 20]
    min_samples_split: [2, 5, 10]
    min_samples_leaf: [1, 2, 4]

grid_search:
  cv: 5
  scoring: neg_mean_squared_error
  verbose: 2
  n_jobs: -1

data_split:
  test_size: 0.2
  random_state: 42

model_output: rf_model.pkl
