name: All pipeline


on:
  push:
    branches:
      - main

jobs:
  integration:  # Model Training, Testing, and Logging
    runs-on: ubuntu-latest
    env:
      connection_string: ${{ secrets.connection_string }}
      raw_data_container_name: ${{ secrets.raw_data_container_name }}
      raw_data_name: ${{ secrets.raw_data_name }}
      cloud_remote: ${{ secrets.cloud_remote }}  # like aws_remote
      dvc_container_name_path: ${{ secrets.dvc_container_name_path }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: DVC Initialize
        run: |
          pip install dvc==3.58.0 
          dvc init
          dvc status

      # - name: Setup Azure CLI
      #   uses: azure/setup-cli@v2

      - name: Start Development Process (Training, Testing)
        run: dvc repro

      - name: Logging (Data versions)
        run: |
          dvc remote add -f $cloud_remote $dvc_container_name_path
          dvc modify $cloud_remote connection_string $connection_string
          dvc push


