name: All pipeline


on:
  push:
    branches:
      - main

jobs:
  Integration:  # Model Training, Testing, and Logging
    runs-on: ubuntu-latest
    env:
      connection_string: ${{ secrets.connection_string }}
      raw_data_container_name: ${{ secrets.raw_data_container_name }}
      raw_data_name: ${{ secrets.raw_data_name }}
      cloud_remote: ${{ secrets.cloud_remote }}  # like aws_remote
      dvc_container_name_path: ${{ secrets.dvc_container_name_path }}
      mlflow_track_ip: ${{ secrets.mlflow_track_ip }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}


    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: DVC Initialize
        run: |
          pip install dvc==3.58.0 
          dvc init
          dvc status

      # - name: Setup Azure CLI
      #   uses: azure/setup-cli@v2

      - name: Start Development Process (Training, Testing)
        run: dvc repro

      - name: Logging (Data versions)
        run: |
          dvc remote add -d $cloud_remote $dvc_container_name_path
          dvc remote modify $cloud_remote connection_string $connection_string
          dvc push

      - name: Logging (Model Experiments ->  Metadata and Artifacts)
        run: |
          python3 model_logging.py


  Deploymenet:
    runs-on: ubuntu-latest
    steps: 
        - name: Checkout Code
          uses: actions/checkout@v3

        - name: Logging to DockerHub
          run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin


        - name: Building and Pushing image to DockerHub
          run: |
            python3 
            docker build -t sanan25/salary-project-image:latest .
        - name: Checking image
          run: |
            docker images -a

        - name: Deploying
          run: |
            docker push sanan25/salary-project-image:latest


